//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Editors
    {
        public int idEditor { get; set; }
        public string alogin { get; set; }
        public string aPassword { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string EditorImagePath { get; set; }
        public Nullable<int> StoreID { get; set; }
    
        public virtual Stores Stores { get; set; }
    }
}
